name: GitHub-Profile-Summary-Cards

on:
  schedule: # Execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-profile-summary-cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.CARD }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, branch name to push cards, main or master
          BRANCH_NAME: "master"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 8
